from router.api_handler import ServiceHandler
from router.service_router import register_service_handler
from router.service_rewrite import register_service_rewrite
from router.service_router import service_router